# State-specific column mappings for common case
# Format: {'dem': col, 'rep': col, 'oth': col or list or None, 'total': col or None}
# If oth is None, total must be provided to calculate oth = total - dem - rep
# If oth is a list, all columns will be summed
STATE_COLUMNS = {
    "Alabama": {
        "dem": "G24PREDHAR",
        "rep": "G24PRERTRU",
        "oth": ["G24PREIKEN", "G24PREIOLI", "G24PREISTE", "G24PREOWRI"],
        "total": None,
    },
    "Alaska": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Arizona": {"dem": "Harris", "rep": "Trump", "oth": None, "total": "PresTot"},
    "Arkansas": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "California": {
        "dem": "votes_dem",
        "rep": "votes_rep",
        "oth": None,
        "total": "votes_total",
    },
    "Colorado": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Connecticut": {
        "dem": "PresDem",
        "rep": "PresRep",
        "oth": None,
        "total": "PresTot",
    },
    "Delaware": {
        "dem": "DE24Data_K",
        "rep": "DE24Data_D",
        "oth": None,
        "total": "DE24Data_G",
    },
    "District of Columbia": {
        "dem": "DC24Data_D",
        "rep": "DC24Data_R",
        "oth": None,
        "total": "DC24Data_T",
    },
    "Florida": {
        "dem": "Florida__2",
        "rep": "Florida__1",
        "oth": None,
        "total": "Florida__9",
    },
    "Georgia": {
        "dem": "G24PREDHAR",
        "rep": "G24PRERTRU",
        "oth": ["G24PREGSTE", "G24PREICRU", "G24PREIWES", "G24PRELOLI"],
        "total": None,
    },
    "Hawaii": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Idaho": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Illinois": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Indiana": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Iowa": {
        "dem": "votes_dem",
        "rep": "votes_rep",
        "oth": None,
        "total": "votes_tota",
    },
    "Kansas": {"dem": "DHarris", "rep": "RTrump", "oth": "Other", "total": None},
    "Kentucky": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Louisiana": {
        "dem": "G24PREDHAR",
        "rep": "G24PRERTRU",
        "oth": [
            "G24PRELOLI",
            "G24PREOCRU",
            "G24PREOFRU",
            "G24PREOKEN",
            "G24PREOPRE",
            "G24PREOSON",
            "G24PREOSTE",
            "G24PREOTER",
            "G24PREOWES",
        ],
        "total": None,
    },
    "Maine": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Maryland": {
        "dem": "G24PRESD",
        "rep": "G24PRESR",
        "oth": "G24PRESO",
        "total": None,
    },
    "Massachusetts": {
        "dem": "votes_dem",
        "rep": "votes_rep",
        "oth": None,
        "total": "votes_total",
    },
    "Michigan": {
        "dem": "votes_dem",
        "rep": "votes_rep",
        "oth": None,
        "total": "votes_total",
    },
    "Minnesota": {
        "dem": "MNPrecinct",
        "rep": "MNPrecin_1",
        "oth": None,
        "total": "MNPrecin_2",
    },
    "Mississippi": {
        "dem": "PresDem",
        "rep": "PresRep",
        "oth": None,
        "total": "PresTot",
    },
    "Missouri": {
        "dem": "HARRIS - D",
        "rep": "TRUMP - RE",
        "oth": None,
        "total": "PRESTOT",
    },
    "Montana": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Nebraska": {"dem": "PresDem", "rep": "PresRep", "oth": "PresOth", "total": None},
    "Nevada": {
        "dem": "NVData24_1",
        "rep": "NVData24_2",
        "oth": None,
        "total": "NVData24_3",
    },
    "New Hampshire": {
        "dem": "PresDem",
        "rep": "PresRep",
        "oth": None,
        "total": "PresTot",
    },
    "New Jersey": {
        "dem": "votes_dem",
        "rep": "votes_rep",
        "oth": None,
        "total": "votes_total",
    },
    "New Mexico": {
        "dem": "NMData24_1",
        "rep": "NMData24_2",
        "oth": None,
        "total": "NMData24_3",
    },
    "New York": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "North Carolina": {
        "dem": "PRESDEM",
        "rep": "PRESREP",
        "oth": None,
        "total": "PRESTOTAL",
    },
    "North Dakota": {
        "dem": "PresDem",
        "rep": "PresRep",
        "oth": None,
        "total": "PresTot",
    },
    "Oklahoma": {
        "dem": "OK24Data_H",
        "rep": "OK24Data_T",
        "oth": None,
        "total": "OK24Data_G",
    },
    "Ohio": {
        "dem": "PresDem",
        "rep": "PresRep",
        "oth": None,
        "total": "PresTot",
    },  # Has NaN - will error correctly
    "Oregon": {"dem": "USP24D", "rep": "USP24R", "oth": None, "total": "USP24Tot"},
    "Pennsylvania": {
        "dem": "votes_dem",
        "rep": "votes_rep",
        "oth": None,
        "total": "votes_total",
    },
    "Rhode Island": {
        "dem": "PresDem",
        "rep": "PresRep",
        "oth": None,
        "total": "PresTot",
    },
    "South Carolina": {"dem": "Harris", "rep": "Trump", "oth": None, "total": "Total"},
    "South Dakota": {
        "dem": "G24PRESD",
        "rep": "G24PRESR",
        "oth": None,
        "total": "G24PRESTOT",
    },
    "Tennessee": {
        "dem": "votes_dem",
        "rep": "votes_rep",
        "oth": None,
        "total": "votes_total",
    },
    "Texas": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "Utah": {
        "dem": "votes_dem",
        "rep": "votes_rep",
        "oth": None,
        "total": "votes_total",
    },
    "Vermont": {
        "dem": "VTData24_K",
        "rep": "VTData24_D",
        "oth": None,
        "total": "VTData24_T",
    },
    "Virginia": {
        "dem": "G24PRESD",
        "rep": "G24PRESR",
        "oth": "G24PRESO",
        "total": None,
    },
    "Washington": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
    "West Virginia": {
        "dem": "PresDem",
        "rep": "PresRep",
        "oth": None,
        "total": "PresTot",
    },
    "Wisconsin": {
        "dem": "votes_dem",
        "rep": "votes_rep",
        "oth": None,
        "total": "votes_tota",
    },
    "Wyoming": {"dem": "PresDem", "rep": "PresRep", "oth": None, "total": "PresTot"},
}
